[package]
name = "zune-image-codec-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
zune-core = "0.4.12"
zune-image = { version = "0.4.15" }
criterion = { version = "0.4" }

[[bench]]
name = "zune_image_codec_benchmark"
harness = false
